# Generated by Django 5.2.4 on 2025-11-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_campus_classe_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='detalhes',
            field=models.CharField(blank=True, default='NSA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='numero',
            field=models.IntegerField(unique=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='cidade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='campus',
            name='endereco',
            field=models.CharField(max_length=150, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
