# Generated by Django 5.2.4 on 2025-11-13 21:44

import cadastros.validators
import django.db.models.deletion
import localflavor.br.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_alter_atividade_detalhes_alter_atividade_numero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('justificativa', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Progressao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateField(verbose_name='Data inicial')),
                ('data_final', models.DateField(verbose_name='Data final')),
                ('observacao', models.CharField(max_length=150, verbose_name='Observação')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Comprovante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('data', models.DateField()),
                ('data_final', models.DateField(verbose_name='Data final')),
                ('arquivo', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.atividade')),
                ('progressao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.progressao')),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=50, verbose_name='Nome completo')),
                ('matricula', models.CharField(help_text='Formato esperado: XX-NNNN (ex: AB-1234)', max_length=7, unique=True, validators=[cadastros.validators.validate_matricula], verbose_name='Matrícula')),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14, unique=True, verbose_name='CPF')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalhes', models.CharField(max_length=150)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.status')),
            ],
        ),
    ]
