# Generated by Django 5.2.4 on 2025-11-14 21:15

import cadastros.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_campo_nome_alter_classe_nome_alter_status_nome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comprovante',
            name='ultima_modificacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificação'),
        ),
        migrations.AddField(
            model_name='comprovante',
            name='usuario',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progressao',
            name='usuario',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='situacao',
            name='movimentado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Movimentado em'),
        ),
        migrations.AddField(
            model_name='situacao',
            name='movimentado_por',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Movimentado por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='situacao',
            name='progressao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cadastros.progressao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='validacao',
            name='comprovante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cadastros.comprovante'),
        ),
        migrations.AddField(
            model_name='validacao',
            name='validado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Validade em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='validacao',
            name='validado_por',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Validade por'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atividade',
            name='pontos',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='comprovante',
            name='arquivo',
            field=models.FileField(upload_to=cadastros.models.user_path),
        ),
        migrations.AlterField(
            model_name='comprovante',
            name='data_final',
            field=models.DateField(blank=True, help_text='Informar apenas se o comprovantefor relativo a um período', null=True, verbose_name='Data final'),
        ),
        migrations.AlterField(
            model_name='comprovante',
            name='progressao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.progressao', verbose_name='Progressão'),
        ),
        migrations.AlterField(
            model_name='comprovante',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='progressao',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.classe', verbose_name='Classe pretendida'),
        ),
        migrations.AlterField(
            model_name='validacao',
            name='justificativa',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='validacao',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterUniqueTogether(
            name='campus',
            unique_together={('cidade', 'endereco')},
        ),
    ]
