# Generated by Django 5.2.4 on 2025-11-16 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_comprovante_ultima_modificacao_comprovante_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validacao',
            name='comprovante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.comprovante'),
        ),
    ]
